"""Secondary processing script, reads in the parquet files generated by
nx_to_parquet and tags both edges and nodes with elevation data. This
requires that a cassandra cluster be available (see relevation repo) and
the relevant lidar files have been ingested."""

from refinement.containers import TaggingConfig
from refinement.enricher import GraphEnricher

# TODO: Investigate whether using graphframes api while tagging improves
#       performance, as filtering edges is currently an expensive operation

config = TaggingConfig(
    data_dir="/home/ross/repos/refinement/data",
    elevation_interval=10,
    max_condense_passes=5,
)

enricher = GraphEnricher(config)
enricher.enrich_graph()
